  services:
    db:
      container_name: portfolio
      image: postgres
      environment:
        POSTGRES_USER: wilyendri
        POSTGRES_PASSWORD: 21043600
        PGDATA: /data/postgres
      volumes:
        - db:/data/postgres
      ports:
        - "5332:5432"
      networks:
        - db
      restart: unless-stopped
  networks:
    db:
      driver: bridge
  volumes:
    db: