server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${JAWSDB_URL}
    username: ${JAWSDB_USERNAME}
    password: ${JAWSDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: wilyendri@gmail.com
    password: ${EMAIL-PSSW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true