  server:
    port: ${PORT:8080}

  spring:
  datasource:
    url: ${JAWSDB_URL}
    username: ${JAWSDB_USERNAME}
    password: ${JAWSDB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
